### PR TITLE
Add simple speaker example

### PR DESCRIPTION
**Pull request by auchenberg**
This PR adds a simple speaker example, so you don't have to use SOX.

### CODE REVIEW

**Comment by watson** [comment]
@auchenberg I just fixed the build errors on master - else these Pull Requests become a nightmare to maintain ;) Can I get you to do me favour and just rebase with the latest master?

**Comment by auchenberg** [comment]
Done

**Comment by watson** [comment]
@auchenberg seems like the `speaker` module doesn't compile out of the box on Travis-CI. Looking at their own `.travis.yml` file it seems trivial to fix it: https://github.com/TooTallNate/node-speaker/blob/fe32912b2596d15a9eb2378e1fc855f361d258fc/.travis.yml#L11

**Comment by watson** [comment]
Pure awesomeness :smiley:

**Pull request merged**
